#!/bin/bash

if cat ./usuarios | grep "^$1$" > /dev/null ; then
	if cat 	./usuarios | grep "^$2$" > /dev/null ; then
		echo $3 >> buzones/$1/out/$2
	else
		echo "Destinatario no existe"
	fi
else
	echo "El remitente no existe"
fi
 
