#!/bin/bash
touch ./usuarios
if cat ./usuarios | grep "^$1$" > /dev/null ; then
	echo "$1 exists"
	exit 1
else
	if echo $1 | grep -E "[^0-9a-zA-Z]" > /dev/null ; then
		echo "$1 contains invalid characters."
		exit 1
	else
		echo $1 >> ./usuarios
	fi
fi


