#!/bin/bash
childs=$(ps -e -o ppid | sed -e 1d | sort | uniq -c | tr -s ' ' ':')
max=$(echo -e "$childs" | sort -k2 -n -t':' | tail -1 | cut -f2 -d':')

for process in $childs
do
	if [ $(echo $process | cut -f2 -d':') -eq $max ] ; then
		echo $process | cut -f3 -d':'
	fi
done
